services:
  - type: web
    name: second-certainty
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html